services:

  db:
    image: mysql:8.0
    container_name: nextgrc_db
    restart: always
    environment:
      MYSQL_DATABASE: next-v2-
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nextgrc
      MYSQL_PASSWORD: nextgrc123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextgrc_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - VITE_DEV_SERVER_URL=http://localhost:5173
      - APP_KEY=base64:qDJ8GbWzBGyShaFX+CrxT6RcXxaBixc3diGp4x2Ocqk=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=next-v2-
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - ML_SERVICE_URL=http://flask:5000
    depends_on:
      - db
    ports:
      - "8000:9000"

  vite:
    build:
      context: .
      dockerfile: docker/Dockerfile.node  
    container_name: nextgrc_vite
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules              
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: nextgrc_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - vite

  flask:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: nextgrc_flask
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./ml:/app
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  node-exporter:
    image: prom/node-exporter:latest
    container_name: nextgrc_node_exporter
    restart: always
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: nextgrc_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: nextgrc_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db_data:
  prometheus_data:
  grafana_data: